openapi: 3.0.3
info:
  title: STD24212
  description: "This is a specification of STD24212"
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /ping:
    get:
      summary: Ping endpoint
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: "pong"