openapi: 3.0.3
info:
  title: STD24212
  description: "This is a specification of STD24212"
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /ping:
    get:
      summary: Ping endpoint
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: "pong"

  /cars:
    get:
      summary: Recupérer la liste de toutes les voitures
      responses:
        '200':
          description: Liste des voitures
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'

  /cars/{id}:
    get:
      summary: Avoir le car par id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: L'identifiant du voiture
      responses:
        '200':
          description: Car details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
        '404':
          description: Car not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "L'identifiant fourni n'est pas trouvé dans la liste"